Learn/Learn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings  # new
from practice import views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', views.home,  name ='home'),

    path('index/', views.index,  name="index"),
    path('my_template/', views.my_template,  name="my_template"),
    
    path('more/', include('more.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Learn/more/urls.py
from django.urls import path
from . import views

app_name = 'more'

urlpatterns = [
    
    path('', views.all_mores,  name ='all_mores'),
    path('<int:more_id>/', views.detail,  name ='detail'),
    # path('post_new/', views.post_new, name='post_new'),
    # path('', views.post_detail,  name ='post_detail'),
    # path('<int:post_id>/', views.post_edit,  name ='post_edit'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/', views.post_edit, name='post_edit'),
    path('post/<int:pk>/detail/', views.post_detail, name='post_detail'),


]

Learn/more/models.py
from django.db import models
from django.utils import timezone

class More(models.Model):
    title =models.CharField(max_length=100)
    description =models.TextField(max_length=10000)
    date = models.DateField()
    
    def __str__(self): 
        return  self.title
# Create your models here.

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

Learn/practice/models.py
from django.db import models
from embed_video.fields import EmbedVideoField
from . validators import file_size

class Project(models.Model):
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='static/practice/')
    url = models.URLField(blank=True)
    
    def __str__(self): 
        return  self.title + self.description

class Video(models.Model):
    caption =models.CharField(max_length=200)
    video = models.FileField(upload_to='static/practice/',validators=[file_size])   
    def __str__(self):
        return self.caption 
    

class Item(models.Model):
    video = EmbedVideoField()     

    def __str__(self):
        return self.video

Learn/more/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

Learn/practice/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from . models import Video

class Video_form(forms.ModelForm):
    class Meta:
        model = Video
        fields =("caption","video")

Learn/more/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .forms import PostForm
from .models import More,Post


def all_mores(request):
    post =Post.objects.all()
    mores =More.objects.order_by('-date') [:3]
    return render(request, 'more/all_mores.html', {'mores':mores , 'post':post})


def detail(request, more_id):
    more = get_object_or_404(More, pk=more_id)
    return render(request, 'more/detail.html', {'more':more}) 




# from .models import Post

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.publish()
            return redirect('post_edit', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'more/post_detail.html', {'form': form})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'more/post_edit.html', {'post': post})

def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'more/post_edit.html', {'form': form})

Learn/practice/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.core.files.storage import default_storage
from django.http import HttpResponseRedirect


from .models import Project,Video
from .forms import Video_form 
from .models import Item

def home (request):
    projects = Project.objects.all()
    return render(request, 'practice/home.html',{'projects':projects})



def index(request):
    all_video=Video.objects.all()
    form = Video_form()
    if request.method == 'POST':
        form = Video_form(data=request.POST,files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponse("Upload successful")
        # else:
    return render(request, 'practice/index.html', {'form':form, 'all_video':all_video})    


def my_template(request):
    # Query the Item model to get the video object
    item = Item.objects.all()  # Assumes you have an Item model with a video_url field
    return render(request, 'practice/my_template.html', {'item': item})


# def upload_item(request):
#     if request.method == 'POST':
#         form = ItemForm(request.POST, request.FILES)
#         if form.is_valid():
#             # Extract the uploaded video file from the form
#             video_file = request.FILES.get('video_file')
            
#             # Save the video file to a temporary location
#             # You can use Django's `default_storage` to handle file storage
#             video_path = default_storage.save('temp/' + video_file.name, video_file)

#             # Construct the video URL or file path and save it to the model
#             video_url = default_storage.url(video_path)
#             item = form.save(commit=False)
#             item.video_url = video_url
#             item.save()
            
#             # Redirect to success page or perform other actions
#             return HttpResponseRedirect('/success/')
#     else:
#         form = ItemForm()
#     return render(request, 'upload_item.html', {'form': form})

# # # frank
# Frank@07


# Create your views here.

Learn/more/templates/more/all_mores.html
{% extends 'practice/base.html' %}

{% load static %}

{% block content %}

<h1 id="moretitle" class="font-weight-bold text-center">Blog</h1>

<h3 class="text-center mb-5">Frank has done {{ mores.count }} YouTube video{{ mores.count|pluralize }}</h3>

{% for more in mores %}
<div class="row justify-content-center my-3">
  <div class="col-md-10">
    <a href="{% url 'more:detail' more.id %}">

      <h2>{{ more.title }}</h2>
    </a>
    <h5 class="text-muted">{{ more.date|date:'M d Y'|upper }}</h5>
    <h4>{{ more.description|striptags|truncatechars:30 }}</h4>
  </div>
</div>

{% endfor %}
<!-- &tk&i2r!mJAXmVHSWp
   password for vasMall -->
{% endblock content %}
<!-- {% include 'more/post_detail.html' %} -->
<!-- {% comment %} {% extends 'practice/base.html' %}  

 
{% block content %}
    

<h1>Create horizontal</h1>

<h2>Frank has written {{mores.count}} more posts about forex{{mores.count|pluralize}}</h2>


<a href="{% url 'home' %}">Back Home</a>

{% for more in mores %}
{% comment %} We add more column detail because in the URL We set app name Equals to Blog.So in the all_more.HTML if we are setting there you are link for the blog title.We have to say.More:id  because if you have many apps in the project.It will cause confusion if we don't specify which app.Name we want there you are to map to. {% endcomment %
<a href= "{% url 'more:detail' more.id %}"><h2>{{more.title}}</h2></a>
<p>{{more.date|date:'M d Y'|upper}}</p>
<p>{{more.description|striptags|truncatechars:10}}</p>

{% endfor %}

{% endblock content%} {% endcomment %} -->

Learn/more/templates/more/detail.html
{% load static %}

{% block content %}

<h1 class="text-center mt-5" id="moredetailtitle">{{ more.title }}</h1>

<h5 class="text-center text-muted mb-5">{{ more.date|date:'F jS Y' }}</h5>

<p>{{ more.description|safe }}</p>

{% endblock %}
<!-- {% comment %} {% extends 'practice/base.html' %} 


{% block content %}
    

<h1>{{more.title}}</h1> 
<h2>---{{ more.date|date:'F jS Y' }}---</h2> 
<h1>{{more.description|safe}}</h1> 
{% endblock content %} {% endcomment %} -->

Learn/more/templates/more/post_detail.html
<!-- {% extends 'practice/base.html' %} -->

{% block content %}
    <div class="post">
        <div class="date">
            {{ post.published_date }}
        </div>
  
        <h1>{{ post.title }}</h1>
    
 
        <p>{{ post.text }}</p>
    </div>
{% endblock %}

Learn/more/templates/more/post_edit.html
{% block content %}
    <h1>New post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

Learn/practice/templates/practice/base.html
<!-- {% comment %} <!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          {% comment %} <a class="navbar-brand" href="#">Navbar</a> {% endcomment %
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              {% comment %} <li class="nav-item">
                <a class="nav-link" href="#">About</a>
              </li> {% endcomment %
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              {% comment %} <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
              </li> {% endcomment %
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
    </nav>

     
    {% block content %}
        
    {% endblock content %}
        
   
 
 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>

  </body>
</html>  {% endcomment %} -->

{% load static %}

<!doctype html>
<html lang="en">
  
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"  integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    
    
    <link rel="stylesheet" href="{% static "practice/custom.css" %}">
    
    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
    
    <link rel="icon" type="image/png" href="{% static "practice/CV.jpg" %}">

  <title>Vasee Nyho</title>
  </head>

<body>
  <div id="fb-root"></div>
  <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v16.0" nonce="WXnrKRj8"></script>
  <nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static "practice/CV.jpg" %}" width="30" height="30" class="d-inline-block align-top" alt="Frank's Logo">
        <span>Vasee Nyho</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% static "practice/resum.pdf" %}">resume</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.linkedin.com/in/frank-adiamah-ab3221257?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BM%2F6x%2FES0SVWRRyEalZomgw%3D%3D" >LinkedIn</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://youtu.be/_irji7FhG9Y" target="_blank">YouTube</a>
          </li>
          <li>
          <div class="fb-page" data-href="https://www.facebook.com/facebook" data-tabs="timeline" 
          data-width="5px" data-height="10px" data-small-header="true" data-adapt-container-width="true"
          data-hide-cover="false" data-show-facepile="true">   
          <blockquote cite="https://www.facebook.com/facebook" class="fb-xfbml-parse-ignore">
          <a href="https://www.facebook.com/facebook">Facebook</a></blockquote></div>
          </li>
          
          <!-- <li class="nav-item">
            <a class="nav-link" href="https://www.facebook.com/profile.php?id=100071802701048" >Facebook</a>
          </li> -->
          <li class="nav-item">
            <a class="nav-link" href="https://twitter.com/VaseeNyho" target="_blank">Twitter</a>
          </li>
          <!-- <li class="nav-item">
            <a class="nav-link" href="{% url 'index' %}" >Videos</a>
          </li> -->
          <!-- target="_blank" this is used to send the user to a different tab in the browser -->
          <li>
            <a role="button" href="{% url 'index' %}" class="btn btn-primary">Video</a>
          </li>
          <li>
            <a role="button" href="{% url 'my_template' %}" class="btn btn-primary">YouTube Upload</a>
          </li>
          <li>
          <a role="button" href="{% url 'more:all_mores' %}" class="btn btn-primary">Blog</a>
        </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %} 
    
    {% endblock content %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <div id="fb-root"></div>
</body>

</html>

Learn/practice/templates/practice/home.html
{% extends "practice/base.html" %}

{% load static %}


{% block content %}
{% load embed_video_tags %}

<div class="row justify-content-center my-3">
  <div class="col-5">
    <img src="{% static 'practice/frank.jpg' %}" class="img-fluid" width ="200" height="200">
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
    <h1 id="hometext" class="font-weight-sans-serif"> Frank Adiamah is computer programmer and know more about software and hardware configurations.
      
      <h2 id="hometext" class="font-weight-sans-serif">He is the owner of <strong>Chat C.</strong> A social Media room page</h2>
      😊</h1>
  </div>

</div>

<h2 class="mt-5">Portfolio</h2>
<hr/>

<div class="row">
  {% for project in projects %}
  <div class="col-lg-4 col-md-6">

    {% if project.url %}
    <a href="{{ project.url }}">
      <img src="{{ project.image.url }}" class="img-fluid mb-2" width="200em" height="200em">
    </a>
    {% else %}

    <img src="{{ project.image.url }}" class="img-fluid mb-2" width="200em" height="200em" >
    {% endif %}
    <h3>{{ project.title }}</h3>
    <p>{{ project.description }}</p>

  </div>
  {% endfor %}
</div>
<hr/>

<!-- <div class="fb-post" data-href="https://web.facebook.com/profile.php?id=100071802701048"
data-width="500" data-show-text="true"></div> -->

<div class="class">
<li>
  <div class="fb-page" data-href="https://www.facebook.com/facebook" data-tabs="timeline" 
  data-width="100%" data-height="100%" data-small-header="true" data-adapt-container-width="true"
  data-hide-cover="false" data-show-facepile="true">   
  <blockquote cite="https://web.facebook.com/profile.php?id=100071802701048" class="fb-xfbml-parse-ignore">
  <a href="https://web.facebook.com/profile.php?id=100071802701048">Facebook</a></blockquote></div>
  </li>
  <div class="fb-page" data-href="https://web.facebook.com/profile.php?id=100071802701048" data-tabs="timeline" data-width="180 to 200" data-height="" data-small-header="true" data-adapt-container-width="true"
  data-hide-cover="false" data-show-facepile="false"></div>
  
  <div class="video" >

<div class="row">
  {% for item in items %}
  <div class="col-md-4, col-sm-6 mb-4">
    <div class="video-container">
      {% video item.video as my_video %}
        <video controls width="70%" height="70%">
          <source src="{{ my_video.url }}" type="{{ my_video.backend }}">
          Your browser does not support the video tag.
        </video>
      {% endvideo %}
    </div>
{% video my_video "small" %}

{% video my_video '800x600' %}

  </div>
  {% endfor %}
</div>

</div>
{% endblock %}

Learn/practice/templates/practice/index.html
{% extends 'practice/base.html' %}

{% block content %}





<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3 mt-5">
      <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="form__group form__group">

        <label form="">Caption</label>
        <input id="text" name="text" type="text" placeholder="Please your caption" />

        <button class="btn btn-success btn-lg mt-3 mb-3">Upload</button>
        </div>
      </form>
    </div>
  </div>
  <div class= "row">
    {% for x in all_video %}
      <div class="col-md-4 mt-3">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">{{ x.caption }}</h5>
            <video class="embed-responsive embed-responsive-16by9" controls="controller">
              <source src="{{ x.video.url }}" type="video/mp4">
            </video>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

Learn/practice/templates/practice/my_template.html
<!-- {% extends 'practice/base.html' %} -->

{% block content %}

{% load embed_video_tags %}


<!-- The video tag: -->
{% video item.video as my_video %}
  URL: {{ my_video.url }}
  Thumbnail: {{ my_video.thumbnail }}
  Backend: {{ my_video.backend }}

  {% video my_video "small" %}
{% endvideo %}

<!-- Or embed shortcut: -->
{% video my_video '800x600' %}
<!-- <div class="row">
  {% for item in items %}   
  <div class="col-md-4, col-sm-6 mb-4">
    <div class="video-container">
      {% video item.video as my_video %}
        <video controls width="70%" height="70%">
          <source src="{{ my_video.url }}" type="{{ my_video.backend }}">
          Your browser does not support the video tag.
        </video>
        {% endvideo %}
    </div>
      {% video my_video "small" %}
      {% video my_video '800x600' %}
      
  </div>
    {% endfor %}
</div> -->
  
{% endblock %}

Learn/practice/templates/practice/upload_item.html
<!-- {% block content %}


<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <label for="{{ form.video_file.id_for_label }}">Video File:</label>
        {{ form.video_file }}
        <small class="form-text text-muted">Upload a video file</small>
    </div>
    <button type="submit" class="btn btn-primary">pload</button>
  </form>
  {% endblock %}   -->